### ISSUE TITLE
No croit images available - Retry

### ISSUE THREAD

**Issue by wangy8961** [croit/vagrant-demo#4]
Hello, I follow this tutorial to build a demo, but I get a problem when run "vagrant up ceph1" the VM can not found PXE boot images (vmlinuz and initrd.img)

[problem](http://www.madmalls.com/api/medias/uploaded/2019-01-28-15-56-36-croit-vagrant-ceph2-1548661411664-22370-running-oracle-vm-virtualbox-3d864af0.png)

**Comment by emmericp** [comment]
Can you please check the state of the image in the UI?

Servers -> Images

**Comment by ghost** [comment]
Vagrant file probably needs to be updated:
 ceph1: Downloading: https://vagrantcloud.com/c33s/boxes/empty/versions/0.1.0/providers/virtualbox.box
    ceph1: Download redirected to host: c33s.net
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found

**Comment by emmericp** [comment]
Looks like https://app.vagrantup.com/c33s/boxes/empty is dead; changed to https://app.vagrantup.com/q2p/boxes/empty


(The original issue here is unrelated)
