### ISSUE TITLE
ceph not installed on croit vm

### ISSUE THREAD

**Issue by ghost** [croit/vagrant-demo#6]
vagrant@stretch:~$ ceph status
-bash: ceph: command not found

Installed ceph manually
agrant@stretch:~$ sudo apt install ceph
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  ceph-base ceph-common ceph-mon ceph-osd cryptsetup-bin gdisk javascript-common libaio1 libbabeltrace-ctf1 libbabeltrace1
  libboost-iostreams1.62.0 libboost-program-options1.62.0 libboost-random1.62.0 libboost-regex1.62.0 libboost-system1.62.0
  libboost-thread1.62.0 libcephfs1 libdw1 libfcgi-bin libfcgi0ldbl libgoogle-perftools4 libjs-jquery libleveldb1v5 libnspr4 libnss3 libopts25
  libparted2 librados2 libradosstriper1 librbd1 libreadline5 librgw2 libsnappy1v5 libtcmalloc-minimal4 libunwind8 ntp parted python-blinker
  python-cephfs python-cffi-backend python-chardet python-click python-colorama python-cryptography python-enum34 python-flask python-idna
  python-ipaddress python-itsdangerous python-jinja2 python-markupsafe python-openssl python-pkg-resources python-pyasn1 python-pyinotify
  python-rados python-rbd python-requests python-setuptools python
<snip>

**Comment by MatthiasGrandl** [comment]
Ceph is not installed on the VM itself. The management node is always inside a docker container, so while inside the VM `sudo docker exec -it croit bash`. Now you should have full access to Ceph. Hope this helps. We are in the process of updating our documentation. Sorry for the inconvenience.
