### ISSUE TITLE
Terminal window doesn't appear to work

### ISSUE THREAD

**Issue by ghost** [croit/vagrant-demo#8]
Tried to connect via terminal to generate ceph.client.admin.keyring manually but terminal is unresponsive. Is there a way to ssh into the ceph nodes to manually configure missing items from demo?

**Comment by MartinVerges** [comment]
fixed the terminal, sorry for the inconvenience. A portforward was missing.

you can use 

```
$ vagrant ssh
$ sudo su
$ docker exec -it croit bash
$ ssh 192.168.0.XXX
```

to use ssh without your own keys.
